services:

  db:
    image: postgres:17
    restart: always
    ports:
      - 15432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /data/ssd/volumes/postgres:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=200
               -c shared_buffers=8GB
               -c effective_cache_size=24GB
               -c work_mem=64MB
               -c maintenance_work_mem=2GB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
               -c synchronous_commit=off
               -c max_worker_processes=36
               -c min_wal_size=4GB
               -c max_wal_size=16GB
               -c max_parallel_workers_per_gather=18
               -c max_parallel_workers=36
               -c max_parallel_maintenance_workers=4
    environment:
      POSTGRES_PASSWORD: postgres